version: "3.8"

services:
  mediamtx:
    image: bluenviron/mediamtx:latest-ffmpeg
    container_name: ${MEDIAMTX_CONTAINER_NAME:-nsmusics-mediamtx}
    restart: unless-stopped
    env_file: .env
    environment:
      - MTX_RTSPTRANSPORTS=tcp
    ports:
      - "${RTSP_PORT}:8554"
      - "${RTMP_PORT}:1935"
      - "${HTTP_PORT}:8888"
      - "${HTTPS_PORT}:8889"
      - "${SRT_PORT}:8890/udp"
      - "${WEBRTC_PORT}:8189/udp"