version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: app
    restart: unless-stopped
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongodb
    volumes:
      - E:\0_Music:/container/data

  # electron:
  #   build:
  #     context: ../  # 设置构建上下文为上一级目录
  #     dockerfile: NSMusicS-GO/Dockerfile-electron
  #   image: electron
  #   container_name: electron
  #   restart: unless-stopped
  #   env_file: .env
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - E:\0_Music:/container/data

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - C:\Users\Public\Documents\NSMusicS-GO\MongoDB:/data/db

volumes:
  dbdata: