version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - C:\Users\Public\Documents\NSMusicS-GO\MongoDB:/data/db

volumes:
  C:\Users\Public\Documents\NSMusicS-GO\MongoDB: