version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: nsmusics-go
    container_name: nsmusics-go
    restart: unless-stopped
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongodb
    volumes:
      - ${MUSIC_DATA_VOLUME}:/container/data
  mongodb:
    image: mongo:6.0
    container_name: nsmusics-mongodb
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ${MongoDB_DATA_VOLUME}:/data/db