# docker build -t nsmusics-web .
# docker build -t nsmusics-go . 

services:
  web:
    image: nsmusics-go  # 使用已构建的镜像
    container_name: nsmusics-go
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongodb
    volumes:
      - E:\0_Music:/container/data

  electron:
    image: nsmusics-web  # 使用已构建的镜像
    container_name: nsmusics-web
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - E:\0_Music:/container/data

  mongodb:
    image: mongo:6.0
    container_name: nsmusics-mongodb
    restart: unless-stopped
    env_file:
      - .env 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - C:\Users\Public\Documents\NSMusicS-GO\MongoDB:/data/db

volumes:
  dbdata:

# services:
#   web:
#     build:
#       context: NSMusicS-GO/
#       dockerfile: Dockerfile
#     image: app
#     container_name: app
#     restart: unless-stopped
#     env_file:
#       - .env
#     ports:
#       - "${PORT}:${PORT}"
#     depends_on:
#       - mongodb
#     volumes:
#       - E:\0_Music:/container/data

#   electron:
#     build:
#       context: NSMusicS-Electron/
#       dockerfile: Dockerfile
#     image: electron
#     container_name: electron
#     restart: unless-stopped
#     ports:
#       - "5173:5173"
#     volumes:
#       - E:\0_Music:/container/data

#   mongodb:
#     image: mongo:6.0
#     container_name: mongodb
#     restart: unless-stopped
#     env_file:
#       - .env 
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
#       - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
#     ports:
#       - "${DB_PORT}:${DB_PORT}"
#     volumes:
#       - C:\Users\Public\Documents\NSMusicS-GO\MongoDB:/data/db

# volumes:
#   dbdata: